### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by pydanny** [agiliq/django-admin-cookbook#1]
Better sooner rather than later

**Comment by pydanny** [comment]
P.S. I would buy a copy. ;)

**Comment by dezoito** [comment]
Make that two.

**Comment by shabda** [comment]
Done. (CC-BY-SA 4.0)

https://github.com/agiliq/django-admin-cookbook/blob/master/LICENSE

I am going to take you up on the offer to buy the when I put it up for sale :).
